// Source: https://www.sitepoint.com/web-foundations/mime-types-complete-list/

function getMimeType(file){
	switch(file.toLowerCase().substr(file.lastIndexOf('.'))){
	case '.3dm':
	case '.3dmf':
	case '.qd3':
	case '.qd3d':
		return 'x-world/x-3dmf';
	case '.a':
	case '.arc':
	case '.arj':
	case '.bin':
	case '.com':
	case '.dump':
	case '.exe':
	case '.lha':
	case '.lhx':
	case '.lzh':
	case '.lzx':
	case '.o':
	case '.psd':
	case '.saveme':
	case '.uu':
	case '.zoo':
		return 'application/octet-stream';
	case '.aab':
		return 'application/x-authorware-bin';
	case '.aam':
		return 'application/x-authorware-map';
	case '.aas':
		return 'application/x-authorware-seg';
	case '.abc':
		return 'text/vnd.abc';
	case '.acgi':
	case '.htm':
	case '.html':
	case '.htmls':
	case '.htx':
	case '.shtml':
		return 'text/html';
	case '.afl':
		return 'video/animaflex';
	case '.ai':
	case '.eps':
	case '.ps':
		return 'application/postscript';
	case '.aif':
	case '.aifc':
	case '.aiff':
		return 'audio/aiff';
	case '.aif':
	case '.aifc':
	case '.aiff':
		return 'audio/x-aiff';
	case '.aim':
		return 'application/x-aim';
	case '.aip':
		return 'text/x-audiosoft-intra';
	case '.ani':
		return 'application/x-navi-animation';
	case '.aos':
		return 'application/x-nokia-9000-communicator-add-on-software';
	case '.aps':
		return 'application/mime';
	case '.arj':
		return 'application/arj';
	case '.art':
		return 'image/x-jg';
	case '.asf':
	case '.asx':
		return 'video/x-ms-asf';
	case '.asm':
	case '.s':
		return 'text/x-asm';
	case '.asp':
		return 'text/asp';
	case '.asx':
		return 'application/x-mplayer2';
	case '.asx':
		return 'video/x-ms-asf-plugin';
	case '.au':
	case '.snd':
		return 'audio/basic';
	case '.au':
		return 'audio/x-au';
	case '.avi':
		return 'application/x-troff-msvideo';
	case '.avi':
		return 'video/avi';
	case '.avi':
		return 'video/msvideo';
	case '.avi':
		return 'video/x-msvideo';
	case '.avs':
		return 'video/avs-video';
	case '.bcpio':
		return 'application/x-bcpio';
	case '.bin':
		return 'application/mac-binary';
	case '.bin':
		return 'application/macbinary';
	case '.bin':
		return 'application/x-binary';
	case '.bin':
		return 'application/x-macbinary';
	case '.bm':
	case '.bmp':
		return 'image/bmp';
	case '.bmp':
		return 'image/x-windows-bmp';
	case '.boo':
	case '.book':
		return 'application/book';
	case '.boz':
	case '.bz2':
		return 'application/x-bzip2';
	case '.bsh':
	case '.sh':
	case '.shar':
		return 'application/x-bsh';
	case '.bz':
		return 'application/x-bzip';
	case '.c':
	case '.c++':
	case '.cc':
	case '.com':
	case '.conf':
	case '.cxx':
	case '.def':
	case '.f':
	case '.f90':
	case '.for':
	case '.g':
	case '.h':
	case '.hh':
	case '.idc':
	case '.jav':
	case '.java':
	case '.list':
	case '.log':
	case '.lst':
	case '.m':
	case '.mar':
	case '.pl':
	case '.sdml':
	case '.text':
	case '.txt':
		return 'text/plain';
	case '.c':
	case '.cc':
	case '.cpp':
		return 'text/x-c';
	case '.cat':
		return 'application/vnd.ms-pki.seccat';
	case '.ccad':
		return 'application/clariscad';
	case '.cco':
		return 'application/x-cocoa';
	case '.cdf':
		return 'application/cdf';
	case '.cdf':
		return 'application/x-cdf';
	case '.cdf':
	case '.nc':
		return 'application/x-netcdf';
	case '.cer':
	case '.crt':
		return 'application/pkix-cert';
	case '.cer':
	case '.crt':
	case '.der':
		return 'application/x-x509-ca-cert';
	case '.cha':
	case '.chat':
		return 'application/x-chat';
	case '.class':
		return 'application/java';
	case '.class':
		return 'application/java-byte-code';
	case '.class':
		return 'application/x-java-class';
	case '.cpio':
		return 'application/x-cpio';
	case '.cpt':
		return 'application/mac-compactpro';
	case '.cpt':
		return 'application/x-compactpro';
	case '.cpt':
		return 'application/x-cpt';
	case '.crl':
		return 'application/pkcs-crl';
	case '.crl':
		return 'application/pkix-crl';
	case '.crt':
		return 'application/x-x509-user-cert';
	case '.csh':
		return 'application/x-csh';
	case '.csh':
		return 'text/x-script.csh';
	case '.css':
		return 'application/x-pointplus';
	case '.css':
		return 'text/css';
	case '.dcr':
	case '.dir':
	case '.dxr':
		return 'application/x-director';
	case '.deepv':
		return 'application/x-deepv';
	case '.dif':
	case '.dv':
		return 'video/x-dv';
	case '.dl':
		return 'video/dl';
	case '.dl':
		return 'video/x-dl';
	case '.doc':
	case '.dot':
	case '.w6w':
	case '.wiz':
	case '.word':
		return 'application/msword';
	case '.dp':
		return 'application/commonground';
	case '.drw':
		return 'application/drafting';
	case '.dvi':
		return 'application/x-dvi';
	case '.dwf':
		return 'drawing/x-dwf (old)';
	case '.dwf':
		return 'model/vnd.dwf';
	case '.dwg':
		return 'application/acad';
	case '.dwg':
	case '.dxf':
	case '.svf':
		return 'image/vnd.dwg';
	case '.dwg':
	case '.dxf':
	case '.svf':
		return 'image/x-dwg';
	case '.dxf':
		return 'application/dxf';
	case '.el':
		return 'text/x-script.elisp';
	case '.elc':
		return 'application/x-bytecode.elisp (compiled elisp)';
	case '.elc':
		return 'application/x-elc';
	case '.env':
	case '.evy':
		return 'application/x-envoy';
	case '.es':
		return 'application/x-esrehber';
	case '.etx':
		return 'text/x-setext';
	case '.evy':
		return 'application/envoy';
	case '.f':
	case '.f77':
	case '.f90':
	case '.for':
		return 'text/x-fortran';
	case '.fdf':
		return 'application/vnd.fdf';
	case '.fif':
		return 'application/fractals';
	case '.fif':
		return 'image/fif';
	case '.fli':
		return 'video/fli';
	case '.fli':
		return 'video/x-fli';
	case '.flo':
	case '.turbot':
		return 'image/florian';
	case '.flx':
		return 'text/vnd.fmi.flexstor';
	case '.fmf':
		return 'video/x-atomic3d-feature';
	case '.fpx':
		return 'image/vnd.fpx';
	case '.fpx':
		return 'image/vnd.net-fpx';
	case '.frl':
		return 'application/freeloader';
	case '.funk':
	case '.my':
	case '.pfunk':
		return 'audio/make';
	case '.g3':
		return 'image/g3fax';
	case '.gif':
		return 'image/gif';
	case '.gl':
		return 'video/gl';
	case '.gl':
		return 'video/x-gl';
	case '.gsd':
	case '.gsm':
		return 'audio/x-gsm';
	case '.gsp':
		return 'application/x-gsp';
	case '.gss':
		return 'application/x-gss';
	case '.gtar':
		return 'application/x-gtar';
	case '.gz':
	case '.tgz':
	case '.z':
	case '.zip':
		return 'application/x-compressed';
	case '.gz':
	case '.gzip':
		return 'application/x-gzip';
	case '.gzip':
		return 'multipart/x-gzip';
	case '.h':
	case '.hh':
		return 'text/x-h';
	case '.hdf':
		return 'application/x-hdf';
	case '.help':
	case '.hlp':
		return 'application/x-helpfile';
	case '.hgl':
	case '.hpg':
	case '.hpgl':
		return 'application/vnd.hp-hpgl';
	case '.hlb':
		return 'text/x-script';
	case '.hlp':
		return 'application/hlp';
	case '.hlp':
		return 'application/x-winhelp';
	case '.hqx':
		return 'application/binhex';
	case '.hqx':
		return 'application/binhex4';
	case '.hqx':
		return 'application/mac-binhex';
	case '.hqx':
		return 'application/mac-binhex40';
	case '.hqx':
		return 'application/x-binhex40';
	case '.hqx':
		return 'application/x-mac-binhex40';
	case '.hta':
		return 'application/hta';
	case '.htc':
		return 'text/x-component';
	case '.htt':
		return 'text/webviewhtml';
	case '.ice':
		return 'x-conference/x-cooltalk';
	case '.ico':
		return 'image/x-icon';
	case '.ief':
	case '.iefs':
		return 'image/ief';
	case '.iges':
	case '.igs':
		return 'application/iges';
	case '.iges':
	case '.igs':
		return 'model/iges';
	case '.ima':
		return 'application/x-ima';
	case '.imap':
		return 'application/x-httpd-imap';
	case '.inf':
		return 'application/inf';
	case '.ins':
		return 'application/x-internett-signup';
	case '.ip':
		return 'application/x-ip2';
	case '.isu':
		return 'video/x-isvideo';
	case '.it':
		return 'audio/it';
	case '.iv':
		return 'application/x-inventor';
	case '.ivr':
		return 'i-world/i-vrml';
	case '.ivy':
		return 'application/x-livescreen';
	case '.jam':
		return 'audio/x-jam';
	case '.jav':
	case '.java':
		return 'text/x-java-source';
	case '.jcm':
		return 'application/x-java-commerce';
	case '.jfif':
	case '.jfif-tbnl':
	case '.jpe':
	case '.jpeg':
	case '.jpg':
		return 'image/jpeg';
	case '.jfif':
	case '.jpe':
	case '.jpeg':
	case '.jpg':
		return 'image/pjpeg';
	case '.jps':
		return 'image/x-jps';
	case '.js':
		return 'application/x-javascript';
	case '.js':
		return 'application/javascript';
	case '.js':
		return 'application/ecmascript';
	case '.js':
		return 'text/javascript';
	case '.js':
		return 'text/ecmascript';
	case '.jut':
		return 'image/jutvision';
	case '.kar':
	case '.mid':
	case '.midi':
		return 'audio/midi';
	case '.kar':
		return 'music/x-karaoke';
	case '.ksh':
		return 'application/x-ksh';
	case '.ksh':
		return 'text/x-script.ksh';
	case '.la':
	case '.lma':
		return 'audio/nspaudio';
	case '.la':
	case '.lma':
		return 'audio/x-nspaudio';
	case '.lam':
		return 'audio/x-liveaudio';
	case '.latex':
	case '.ltx':
		return 'application/x-latex';
	case '.lha':
		return 'application/lha';
	case '.lha':
		return 'application/x-lha';
	case '.lsp':
		return 'application/x-lisp';
	case '.lsp':
		return 'text/x-script.lisp';
	case '.lsx':
		return 'text/x-la-asf';
	case '.lzh':
		return 'application/x-lzh';
	case '.lzx':
		return 'application/lzx';
	case '.lzx':
		return 'application/x-lzx';
	case '.m':
		return 'text/x-m';
	case '.m1v':
	case '.m2v':
	case '.mp2':
	case '.mp3':
	case '.mpa':
	case '.mpe':
	case '.mpeg':
	case '.mpg':
		return 'video/mpeg';
	case '.m2a':
	case '.mp2':
	case '.mpa':
	case '.mpg':
	case '.mpga':
		return 'audio/mpeg';
	case '.m3u':
		return 'audio/x-mpequrl';
	case '.man':
		return 'application/x-troff-man';
	case '.map':
		return 'application/x-navimap';
	case '.mbd':
		return 'application/mbedlet';
	case '.mc$':
		return 'application/x-magic-cap-package-1.0';
	case '.mcd':
		return 'application/mcad';
	case '.mcd':
		return 'application/x-mathcad';
	case '.mcf':
		return 'image/vasa';
	case '.mcf':
		return 'text/mcf';
	case '.mcp':
		return 'application/netmc';
	case '.me':
		return 'application/x-troff-me';
	case '.mht':
	case '.mhtml':
	case '.mime':
		return 'message/rfc822';
	case '.mid':
	case '.midi':
		return 'application/x-midi';
	case '.mid':
	case '.midi':
		return 'audio/x-mid';
	case '.mid':
	case '.midi':
		return 'audio/x-midi';
	case '.mid':
	case '.midi':
		return 'music/crescendo';
	case '.mid':
	case '.midi':
		return 'x-music/x-midi';
	case '.mif':
		return 'application/x-frame';
	case '.mif':
		return 'application/x-mif';
	case '.mime':
		return 'www/mime';
	case '.mjf':
		return 'audio/x-vnd.audioexplosion.mjuicemediafile';
	case '.mjpg':
		return 'video/x-motion-jpeg';
	case '.mm':
	case '.mme':
		return 'application/base64';
	case '.mm':
		return 'application/x-meme';
	case '.mod':
		return 'audio/mod';
	case '.mod':
		return 'audio/x-mod';
	case '.moov':
	case '.mov':
	case '.qt':
		return 'video/quicktime';
	case '.movie':
	case '.mv':
		return 'video/x-sgi-movie';
	case '.mp2':
		return 'audio/x-mpeg';
	case '.mp2':
	case '.mp3':
		return 'video/x-mpeg';
	case '.mp2':
		return 'video/x-mpeq2a';
	case '.mp3':
		return 'audio/mpeg3';
	case '.mp3':
		return 'audio/x-mpeg-3';
	case '.mpc':
	case '.mpt':
	case '.mpv':
	case '.mpx':
		return 'application/x-project';
	case '.mpp':
		return 'application/vnd.ms-project';
	case '.mrc':
		return 'application/marc';
	case '.ms':
		return 'application/x-troff-ms';
	case '.mzz':
		return 'application/x-vnd.audioexplosion.mzz';
	case '.nap':
	case '.naplps':
		return 'image/naplps';
	case '.ncm':
		return 'application/vnd.nokia.configuration-message';
	case '.nif':
	case '.niff':
		return 'image/x-niff';
	case '.nix':
		return 'application/x-mix-transfer';
	case '.nsc':
		return 'application/x-conference';
	case '.nvd':
		return 'application/x-navidoc';
	case '.oda':
		return 'application/oda';
	case '.omc':
		return 'application/x-omc';
	case '.omcd':
		return 'application/x-omcdatamaker';
	case '.omcr':
		return 'application/x-omcregerator';
	case '.p':
		return 'text/x-pascal';
	case '.p10':
		return 'application/pkcs10';
	case '.p10':
		return 'application/x-pkcs10';
	case '.p12':
		return 'application/pkcs-12';
	case '.p12':
		return 'application/x-pkcs12';
	case '.p7a':
		return 'application/x-pkcs7-signature';
	case '.p7c':
	case '.p7m':
		return 'application/pkcs7-mime';
	case '.p7c':
	case '.p7m':
		return 'application/x-pkcs7-mime';
	case '.p7r':
		return 'application/x-pkcs7-certreqresp';
	case '.p7s':
		return 'application/pkcs7-signature';
	case '.part':
	case '.prt':
		return 'application/pro_eng';
	case '.pas':
		return 'text/pascal';
	case '.pbm':
		return 'image/x-portable-bitmap';
	case '.pcl':
		return 'application/vnd.hp-pcl';
	case '.pcl':
		return 'application/x-pcl';
	case '.pct':
		return 'image/x-pict';
	case '.pcx':
		return 'image/x-pcx';
	case '.pdb':
	case '.xyz':
		return 'chemical/x-pdb';
	case '.pdf':
		return 'application/pdf';
	case '.pfunk':
		return 'audio/make.my.funk';
	case '.pgm':
		return 'image/x-portable-graymap';
	case '.pgm':
		return 'image/x-portable-greymap';
	case '.pic':
	case '.pict':
		return 'image/pict';
	case '.pkg':
		return 'application/x-newton-compatible-pkg';
	case '.pko':
		return 'application/vnd.ms-pki.pko';
	case '.pl':
		return 'text/x-script.perl';
	case '.plx':
		return 'application/x-pixclscript';
	case '.pm':
	case '.xpm':
		return 'image/x-xpixmap';
	case '.pm':
		return 'text/x-script.perl-module';
	case '.pm4':
	case '.pm5':
		return 'application/x-pagemaker';
	case '.png':
	case '.x-png':
		return 'image/png';
	case '.pnm':
		return 'application/x-portable-anymap';
	case '.pnm':
		return 'image/x-portable-anymap';
	case '.pot':
	case '.pps':
	case '.ppt':
	case '.ppz':
		return 'application/mspowerpoint';
	case '.pot':
	case '.ppa':
	case '.pps':
	case '.ppt':
	case '.pwz':
		return 'application/vnd.ms-powerpoint';
	case '.pov':
		return 'model/x-pov';
	case '.ppm':
		return 'image/x-portable-pixmap';
	case '.ppt':
		return 'application/powerpoint';
	case '.ppt':
		return 'application/x-mspowerpoint';
	case '.pre':
		return 'application/x-freelance';
	case '.pvu':
		return 'paleovu/x-pv';
	case '.py':
		return 'text/x-script.phyton';
	case '.pyc':
		return 'application/x-bytecode.python';
	case '.qcp':
		return 'audio/vnd.qcelp';
	case '.qif':
	case '.qti':
	case '.qtif':
		return 'image/x-quicktime';
	case '.qtc':
		return 'video/x-qtc';
	case '.ra':
	case '.ram':
	case '.rm':
	case '.rmm':
	case '.rmp':
		return 'audio/x-pn-realaudio';
	case '.ra':
	case '.rmp':
	case '.rpm':
		return 'audio/x-pn-realaudio-plugin';
	case '.ra':
		return 'audio/x-realaudio';
	case '.ras':
		return 'application/x-cmu-raster';
	case '.ras':
	case '.rast':
		return 'image/cmu-raster';
	case '.ras':
		return 'image/x-cmu-raster';
	case '.rexx':
		return 'text/x-script.rexx';
	case '.rf':
		return 'image/vnd.rn-realflash';
	case '.rgb':
		return 'image/x-rgb';
	case '.rm':
		return 'application/vnd.rn-realmedia';
	case '.rmi':
		return 'audio/mid';
	case '.rng':
		return 'application/ringing-tones';
	case '.rng':
		return 'application/vnd.nokia.ringing-tone';
	case '.rnx':
		return 'application/vnd.rn-realplayer';
	case '.roff':
	case '.t':
	case '.tr':
		return 'application/x-troff';
	case '.rp':
		return 'image/vnd.rn-realpix';
	case '.rt':
	case '.rtf':
	case '.rtx':
		return 'text/richtext';
	case '.rt':
		return 'text/vnd.rn-realtext';
	case '.rtf':
	case '.rtx':
		return 'application/rtf';
	case '.rtf':
		return 'application/x-rtf';
	case '.rv':
		return 'video/vnd.rn-realvideo';
	case '.s3m':
		return 'audio/s3m';
	case '.sbk':
	case '.tbk':
		return 'application/x-tbook';
	case '.scm':
		return 'application/x-lotusscreencam';
	case '.scm':
		return 'text/x-script.guile';
	case '.scm':
		return 'text/x-script.scheme';
	case '.scm':
		return 'video/x-scm';
	case '.sdp':
		return 'application/sdp';
	case '.sdp':
		return 'application/x-sdp';
	case '.sdr':
		return 'application/sounder';
	case '.sea':
		return 'application/sea';
	case '.sea':
		return 'application/x-sea';
	case '.set':
		return 'application/set';
	case '.sgm':
	case '.sgml':
		return 'text/sgml';
	case '.sgm':
	case '.sgml':
		return 'text/x-sgml';
	case '.sh':
		return 'application/x-sh';
	case '.sh':
	case '.shar':
		return 'application/x-shar';
	case '.sh':
		return 'text/x-script.sh';
	case '.shtml':
	case '.ssi':
		return 'text/x-server-parsed-html';
	case '.sid':
		return 'audio/x-psid';
	case '.sit':
		return 'application/x-sit';
	case '.sit':
		return 'application/x-stuffit';
	case '.skd':
	case '.skm':
	case '.skp':
	case '.skt':
		return 'application/x-koan';
	case '.sl':
		return 'application/x-seelogo';
	case '.smi':
	case '.smil':
		return 'application/smil';
	case '.snd':
		return 'audio/x-adpcm';
	case '.sol':
		return 'application/solids';
	case '.spc':
		return 'application/x-pkcs7-certificates';
	case '.spc':
	case '.talk':
		return 'text/x-speech';
	case '.spl':
		return 'application/futuresplash';
	case '.spr':
	case '.sprite':
		return 'application/x-sprite';
	case '.src':
	case '.wsrc':
		return 'application/x-wais-source';
	case '.ssm':
		return 'application/streamingmedia';
	case '.sst':
		return 'application/vnd.ms-pki.certstore';
	case '.step':
	case '.stp':
		return 'application/step';
	case '.stl':
		return 'application/sla';
	case '.stl':
		return 'application/vnd.ms-pki.stl';
	case '.stl':
		return 'application/x-navistyle';
	case '.sv4cpio':
		return 'application/x-sv4cpio';
	case '.sv4crc':
		return 'application/x-sv4crc';
	case '.svr':
	case '.wrl':
		return 'application/x-world';
	case '.svr':
		return 'x-world/x-svr';
	case '.swf':
		return 'application/x-shockwave-flash';
	case '.tar':
		return 'application/x-tar';
	case '.tbk':
		return 'application/toolbook';
	case '.tcl':
		return 'application/x-tcl';
	case '.tcl':
		return 'text/x-script.tcl';
	case '.tcsh':
		return 'text/x-script.tcsh';
	case '.tex':
		return 'application/x-tex';
	case '.texi':
	case '.texinfo':
		return 'application/x-texinfo';
	case '.text':
		return 'application/plain';
	case '.tgz':
		return 'application/gnutar';
	case '.tif':
	case '.tiff':
		return 'image/tiff';
	case '.tif':
	case '.tiff':
		return 'image/x-tiff';
	case '.tsi':
		return 'audio/tsp-audio';
	case '.tsp':
		return 'application/dsptype';
	case '.tsp':
		return 'audio/tsplayer';
	case '.tsv':
		return 'text/tab-separated-values';
	case '.uil':
		return 'text/x-uil';
	case '.uni':
	case '.unis':
	case '.uri':
	case '.uris':
		return 'text/uri-list';
	case '.unv':
		return 'application/i-deas';
	case '.ustar':
		return 'application/x-ustar';
	case '.ustar':
		return 'multipart/x-ustar';
	case '.uu':
	case '.uue':
		return 'text/x-uuencode';
	case '.vcd':
		return 'application/x-cdlink';
	case '.vcs':
		return 'text/x-vcalendar';
	case '.vda':
		return 'application/vda';
	case '.vdo':
		return 'video/vdo';
	case '.vew':
		return 'application/groupwise';
	case '.viv':
	case '.vivo':
		return 'video/vivo';
	case '.viv':
	case '.vivo':
		return 'video/vnd.vivo';
	case '.vmd':
		return 'application/vocaltec-media-desc';
	case '.vmf':
		return 'application/vocaltec-media-file';
	case '.voc':
		return 'audio/voc';
	case '.voc':
		return 'audio/x-voc';
	case '.vos':
		return 'video/vosaic';
	case '.vox':
		return 'audio/voxware';
	case '.vqe':
	case '.vql':
		return 'audio/x-twinvq-plugin';
	case '.vqf':
		return 'audio/x-twinvq';
	case '.vrml':
		return 'application/x-vrml';
	case '.vrml':
	case '.wrl':
	case '.wrz':
		return 'model/vrml';
	case '.vrml':
	case '.wrl':
	case '.wrz':
		return 'x-world/x-vrml';
	case '.vrt':
		return 'x-world/x-vrt';
	case '.vsd':
	case '.vst':
	case '.vsw':
		return 'application/x-visio';
	case '.w60':
	case '.wp5':
		return 'application/wordperfect6.0';
	case '.w61':
		return 'application/wordperfect6.1';
	case '.wav':
		return 'audio/wav';
	case '.wav':
		return 'audio/x-wav';
	case '.wb1':
		return 'application/x-qpro';
	case '.wbmp':
		return 'image/vnd.wap.wbmp';
	case '.web':
		return 'application/vnd.xara';
	case '.wk1':
		return 'application/x-123';
	case '.wmf':
		return 'windows/metafile';
	case '.wml':
		return 'text/vnd.wap.wml';
	case '.wmlc':
		return 'application/vnd.wap.wmlc';
	case '.wmls':
		return 'text/vnd.wap.wmlscript';
	case '.wmlsc':
		return 'application/vnd.wap.wmlscriptc';
	case '.wp':
	case '.wp5':
	case '.wp6':
	case '.wpd':
		return 'application/wordperfect';
	case '.wpd':
		return 'application/x-wpwin';
	case '.wq1':
		return 'application/x-lotus';
	case '.wri':
		return 'application/mswrite';
	case '.wri':
		return 'application/x-wri';
	case '.wsc':
		return 'text/scriplet';
	case '.wtk':
		return 'application/x-wintalk';
	case '.xbm':
		return 'image/x-xbitmap';
	case '.xbm':
		return 'image/x-xbm';
	case '.xbm':
		return 'image/xbm';
	case '.xdr':
		return 'video/x-amt-demorun';
	case '.xgz':
		return 'xgl/drawing';
	case '.xif':
		return 'image/vnd.xiff';
	case '.xl':
	case '.xla':
	case '.xlb':
	case '.xlc':
	case '.xld':
	case '.xlk':
	case '.xll':
	case '.xlm':
	case '.xls':
	case '.xlt':
	case '.xlv':
	case '.xlw':
		return 'application/excel';
	case '.xla':
	case '.xlb':
	case '.xlc':
	case '.xld':
	case '.xlk':
	case '.xll':
	case '.xlm':
	case '.xls':
	case '.xlt':
	case '.xlv':
	case '.xlw':
		return 'application/x-excel';
	case '.xla':
	case '.xls':
	case '.xlw':
		return 'application/x-msexcel';
	case '.xlb':
	case '.xlc':
	case '.xll':
	case '.xlm':
	case '.xls':
	case '.xlw':
		return 'application/vnd.ms-excel';
	case '.xm':
		return 'audio/xm';
	case '.xml':
	case '.ipardata':
		return 'application/xml';
	case '.xml':
		return 'text/xml';
	case '.xmz':
		return 'xgl/movie';
	case '.xpix':
		return 'application/x-vnd.ls-xpix';
	case '.xpm':
		return 'image/xpm';
	case '.xsr':
		return 'video/x-amt-showrun';
	case '.xwd':
		return 'image/x-xwd';
	case '.xwd':
		return 'image/x-xwindowdump';
	case '.z':
		return 'application/x-compress';
	case '.zip':
		return 'application/x-zip-compressed';
	case '.zip':
		return 'application/zip';
	case '.zip':
		return 'multipart/x-zip';
	case '.zsh':
		return 'text/x-script.zsh';
	}
}